package com.fit2081.week8_classroom.data.quizAttempts

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a quiz attempt made by a student.
 *
 * This data class is annotated with @Entity to mark it as a Room database table.
 * The table name is "quiz_attempts".
 */
@Entity(tableName = "quiz_attempts")
data class QuizAttempt(
    /**
     * Unique identifier for the quiz attempt.
     * It is automatically generated by Room.
     */
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,
    /**
     * Identifier of the student who attempted the quiz.
     */
    val studentId: String,
    /**
     * Identifier of the quiz that was attempted.
     */
    val quizId: String,
    val quizDate: String,
    val finalMark: Double
)
